-- Add MFA fields to User table
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "mfaEnabled" BOOLEAN DEFAULT FALSE;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "mfaSecret" VARCHAR(255);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "mfaBackupCodes" JSONB; 